function [result] = getLabels(sort)
    GIS = { ...
        'Bale' 'Mouhoun' 'Nayala' 'Boulkiemde' 'Sanguie' 'Ziro' ...
        'Bougouriba' 'Houet' 'Tuy' 'Gnagna' 'Gourma' 'Komandjoari' ...
        'Kouritenga' 'Kadiogo' 'Ganzourgou' 'Kourweogo' 'Oubritenga' ...
        'Loroum' 'Passore' 'Zondoma' 'Bazega' 'Zoundweogo' 'Bam' ...
        'Namentenga' 'Sanmatenga' 'Kenedougou' 'Leraba' 'Comoe' ...
        'Noumbiel' 'Poni' 'Ioba' 'Sissili' 'Nahouri' 'Boulgou' ...
        'Koulpelogo' 'Kompienga' 'Tapoa' 'Yagha' 'Seno' 'Oudalan' ...
        'Soum' 'Yatenga' 'Sourou' 'Kossi' 'Banwa' };
    
    % Get the correct order of labels
    ndx = 1;
    for item = sort
        labels(ndx) = GIS(item);
        ndx = ndx + 1;
    end
    
    % Sort them properly
    result = categorical(labels);
	result = reordercats(result, labels);
end

